language: erlang

otp_release:
  - 18.1

sudo: false

before_script:
  - git clone https://github.com/elixir-lang/elixir.git
  - cd elixir
  - git checkout v1.3.0-rc.1
  - make compile && cd ..
  - export PATH=$PWD/elixir/bin:$PATH
  - mix local.hex --force
  - mix hex.info
  - mix deps.get
  - mix local.rebar --force

script:
  - mix test
